# Generated by Django 4.2.8 on 2025-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
