# Generated by Django 4.2.8 on 2025-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Accepted Application',
                'verbose_name_plural': 'Accepted Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='PendingApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Application',
                'verbose_name_plural': 'Pending Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='RejectedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Rejected Application',
                'verbose_name_plural': 'Rejected Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.AddField(
            model_name='application',
            name='lead_quality',
            field=models.CharField(choices=[('high', 'High Lead'), ('medium', 'Medium Lead'), ('low', 'Low Lead')], default='medium', max_length=20),
        ),
    ]
