# Generated by Django 4.2.8 on 2025-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_acceptedapplication_pendingapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_status_message',
            field=models.TextField(blank=True, help_text='Custom message from admin (e.g., rejection reason, additional notes). If empty, default status message will be shown.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='lead_quality',
            field=models.CharField(choices=[('high', 'High Lead'), ('medium', 'Medium Lead'), ('low', 'Low Lead')], default='low', help_text='Quality of the lead based on application completeness', max_length=20),
        ),
    ]
