# Generated by Django 4.2.8 on 2025-12-05 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentuniversityvisit',
            options={'ordering': ['-latest_visit_date']},
        ),
        migrations.RenameField(
            model_name='studentuniversityvisit',
            old_name='visited_at',
            new_name='first_visit_date',
        ),
        migrations.AddField(
            model_name='studentuniversityvisit',
            name='latest_visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Duolingo', 'Duolingo'), ('Cambridge', 'Cambridge'), ('SAT', 'SAT'), ('GMAT', 'GMAT'), ('Other', 'Other')], max_length=50)),
                ('test_date', models.DateField()),
                ('validity_years', models.IntegerField(default=2)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
