# Generated by Django 4.2.8 on 2025-11-24 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('country_origin', models.CharField(help_text='Country where this curriculum originated', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Curricula',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Emirate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirates', to='core.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_code'], name='core_countr_iso_cod_9f5dac_idx'),
        ),
        migrations.AddIndex(
            model_name='emirate',
            index=models.Index(fields=['country', 'name'], name='core_emirat_country_c0bec4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emirate',
            unique_together={('name', 'country')},
        ),
    ]
