# Generated by Django 4.2.8 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='country',
            name='core_countr_iso_cod_9f5dac_idx',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='iso_code',
            new_name='country_code',
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country_code'], name='core_countr_country_7a1393_idx'),
        ),
    ]
