# Generated by Django 4.2.8 on 2025-11-24 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('semesters', 'Semesters')], default='years', max_length=20)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
                ('entry_requirements', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_types', to='programs.programlevel')),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('per', models.CharField(choices=[('year', 'Per Year'), ('semester', 'Per Semester'), ('credit', 'Per Credit Hour'), ('program', 'Total Program')], default='year', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='programs.programtype')),
            ],
            options={
                'ordering': ['program_type', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('delivery_type', models.CharField(choices=[('on_campus', 'On Campus'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='on_campus', max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programtype')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['university', 'name'],
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnglishRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('toefl', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('pte', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_requirements', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='programs.program')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
