# Generated by Django 4.2.8 on 2025-11-27 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuitionfee',
            options={'ordering': ['program', 'amount']},
        ),
        migrations.RemoveField(
            model_name='tuitionfee',
            name='program_type',
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='programs.program'),
        ),
    ]
