# Generated by Django 4.2.8 on 2025-11-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_tuitionfee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='program',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='programs.program'),
            preserve_default=False,
        ),
    ]
