# Generated by Django 4.2.8 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishrequirement',
            name='extra_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Additional English requirements (e.g. SAT, Duolingo)'),
        ),
    ]
