# Generated by Django 4.2.8 on 2025-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_englishrequirement_extra_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishrequirement',
            options={'verbose_name': 'English Proficiency Requirement', 'verbose_name_plural': 'English Proficiency Requirements'},
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='ielts',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='pte',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='toefl',
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='custom_range_label',
            field=models.CharField(blank=True, help_text='e.g. 100-200 for SAT/TOEFL', max_length=100),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='listening_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='reading_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='speaking_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='test_type',
            field=models.CharField(choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Duolingo', 'Duolingo'), ('Cambridge', 'Cambridge'), ('SAT', 'SAT'), ('GMAT', 'GMAT'), ('Other', 'Other')], default='IELTS', max_length=50),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='writing_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='englishrequirement',
            name='extra_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details'),
        ),
    ]
