# Generated by Django 4.2.8 on 2025-11-24 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='university_images/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('is_partner', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('established_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('accreditation', models.TextField()),
                ('facilities', models.TextField()),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('university_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('federal', 'Federal')], default='private', max_length=50)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.contactinfo')),
                ('location_emirate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='core.emirate')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisaSponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offers_visa', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_sponsorships', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Visa Sponsorships',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('eligibility', models.TextField()),
                ('coverage', models.TextField()),
                ('renewable', models.BooleanField(default=False)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.university')),
            ],
            options={
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_enrollment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('international_enrollment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('male_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('female_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('faculty_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('academic_year', models.CharField(max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_stats', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Enrollment Statistics',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='UniversityCurriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='core.curriculum')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_curricula', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'University Curricula',
                'unique_together': {('university', 'curriculum')},
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['location_emirate', 'is_partner'], name='universitie_locatio_4257b5_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['university_type'], name='universitie_univers_b78e89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentstat',
            unique_together={('university', 'academic_year')},
        ),
    ]
