# Generated by Django 4.2.8 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentstat',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional statistics'),
        ),
    ]
