# Generated by Django 4.2.8 on 2025-12-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_country_core_countr_iso_cod_9f5dac_idx_and_more'),
        ('universities', '0004_enrollmentstat_extra_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='university',
            name='universitie_univers_b78e89_idx',
        ),
        migrations.AddField(
            model_name='university',
            name='location_city',
            field=models.CharField(blank=True, help_text='City/State name for non-UAE universities (e.g., Sydney, Melbourne)', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='location_emirate',
            field=models.ForeignKey(blank=True, help_text='Select emirate if university is in UAE, otherwise leave blank', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='core.emirate'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['slug'], name='universitie_slug_a72a11_idx'),
        ),
    ]
