# Generated by Django 4.2.8 on 2025-12-05 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_remove_university_universitie_univers_b78e89_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentstat',
            options={'verbose_name_plural': 'Enrollment Statistics'},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentstat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2023-2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='faculty_count',
            field=models.IntegerField(blank=True, help_text='Number of faculty members', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='female_students',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='international_enrollment',
            field=models.IntegerField(blank=True, help_text='Number of international students', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='male_students',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentstat',
            name='total_enrollment',
            field=models.IntegerField(blank=True, help_text='Total number of students', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
