# Generated by Django 4.2.8 on 2025-12-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_country_core_countr_iso_cod_9f5dac_idx_and_more'),
        ('universities', '0006_alter_enrollmentstat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Select country for non-UAE universities', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='core.country'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country'], name='universitie_country_10c12e_idx'),
        ),
    ]
